# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# # Use either `docker-compose` or individual `docker build` commands
# # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy
#
# # Tagging
  - docker tag udagram-api-feed thinhvu2511/udagram-api-feed:v1
  - docker tag udagram-api-user thinhvu2511/udagram-api-user:v1
  - docker tag udagram-frontend thinhvu2511/udagram-frontend:v1
  - docker tag reverseproxy thinhvu2511/reverseproxy:v1

```bash
# # Push
# # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thinhvu2511/udagram-api-feed:v1
  - docker push thinhvu2511/udagram-api-user:v1
  - docker push thinhvu2511/udagram-frontend:v1
  - docker push thinhvu2511/reverseproxy:v1
#
   
