# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# # Use either `docker-compose` or individual `docker build` commands
# # Build
language: node_js
node_js:
  - 13

services:
  - docker

Build:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy
#
Tagging:
  - docker tag udagram-api-feed sudkul/udagram-api-feed:v1
  - docker tag udagram-api-user sudkul/udagram-api-user:v1
  - docker tag udagram-frontend sudkul/udagram-frontend:v1
  - docker tag reverseproxy/reverseproxy:v1

```bash
Push:
# # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sudkul/udagram-api-feed:v1
  - docker push sudkul/udagram-api-user:v1
  - docker push sudkul/udagram-frontend:v1
  - docker push sudkul/reverseproxy:v1
#
   
